# Generated by Django 3.0.8 on 2020-08-09 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='external_author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
